version: '3.2'
networks:
  m-network:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - '9090:9090'
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - m-network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
    - '3000:3000'
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
        - prometheus
    networks:
      - m-network